Repository streamnative/terraform-provider-pulsar, pull requests merged in 2023-07, with the labels that each got.

#93 Update README.md
  README.md
Labels: doc-info-missing

#91 Add retries to permission grant updates on Pulsar topics
  pulsar/resource_pulsar_topic.go
Labels: no-need-doc

#95 fix source/sink connector archive/packageURL support
  go.mod
  go.sum
  pulsar/resource_pulsar_sink.go
  pulsar/resource_pulsar_source.go
Labels: no-need-doc

#96 add sink create & update arguments
  pulsar/resource_pulsar_sink.go
  pulsar/resource_pulsar_sink_test.go
Labels: doc-required

#99 ci: add tmate session for acctest debug
  .github/workflows/acctest.yaml
Labels: no-need-doc

#100 upgrade pulsar to 2.10.4 for test
  README.md
  examples/sinks/main.tf
  examples/sources/main.tf
  hack/pulsarimage/Dockerfile
  hack/pulsarimage/entrypoint.sh
  pulsar/resource_pulsar_sink_test.go
  pulsar/resource_pulsar_source_test.go
  pulsar/testdata/sink/main.tf
  pulsar/testdata/source/main.tf
Labels: no-need-doc

#97 add CustomRuntimeOption,Secrets,SchemaType to Source
  .github/workflows/acctest.yaml
  pulsar/resource_pulsar_sink.go
  pulsar/resource_pulsar_source.go
  pulsar/resource_pulsar_source_test.go
  pulsar/testdata/source/main.tf
  pulsar/util.go
Labels: doc-required

#98 add pulsar_function resource
  hack/pulsar-docker.sh
  pulsar/provider.go
  pulsar/resource_pulsar_function.go
  pulsar/resource_pulsar_function_test.go
  pulsar/testdata/function/main.tf
Labels: doc-required

#101 docs: add version compatibility
  README.md
Labels: doc-info-missing
